<script src="https://giscus.app/client.js"
        data-repo="mrleopvp520/blog_3B_BMF_Leonardo"
        data-repo-id="R_kgDOTsoSmg"
        data-category="General"
        data-category-id="DIC_kwDOTsoSms4DDEu7"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="preferred_color_scheme"
        data-lang="pt"
        crossorigin="anonymous"
        async>
</script>